version: '3'

services:
  miner:
    container_name: miner
    build: .
    ports:
      - 8124:8124
      - 9001:9001
      - 9002:9002
      - 9003:9003
    volumes:
      - /Volumes/wahu/creepMiner:/config
      - /plots/volumes/01:/plots
    environment:
      - AUTO_START=TRUE
      - FRONTAIL=TRUE
    restart: always